version : '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.8.12-management-alpine
    container_name: rabbitmq
    ports:
      - "15672:15672"  # RabbitMQ Management UI
      - "5672:5672"    # RabbitMQ AMQP protocol
    environment:
      RABBITMQ_DEFAULT_USER: Lakshya
      RABBITMQ_DEFAULT_PASS: Lakshya123
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 30s
      timeout: 10s
      retries: 5